#!/bin/bash

echo -n "About to start websockets server. Go to this ip in a web browser: "
ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
/usr/bin/python3 /home/pi/code/robot/server/main.py
